// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trader.Storage.Inventory;

#nullable disable

namespace Trader.Storage.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20231223193553_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trader.Storage.Inventory.Models.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("base_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exchanges");

                    b.ToTable("exchanges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("05a7296f-15fb-4de0-9592-07b5581e1df3"),
                            BaseUrl = "www.deribit.com",
                            Title = "deribit"
                        },
                        new
                        {
                            Id = new Guid("6c7fa016-deb4-4901-8e7a-00c46ecc247e"),
                            BaseUrl = "test.deribit.com",
                            Title = "test.deribit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
