// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trader.Storage.Inventory;

#nullable disable

namespace Trader.Storage.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20231224140137_EditTitleHasData")]
    partial class EditTitleHasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trader.Storage.Inventory.Models.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("base_url");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exchanges");

                    b.ToTable("exchanges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f3534a2-0979-43f9-926b-81fd2275b6bb"),
                            BaseUrl = "www.deribit.com",
                            ResourceName = "deribit.svg",
                            Title = "Deribit"
                        },
                        new
                        {
                            Id = new Guid("4fcf888a-266a-4bd4-b027-8b6868a8b916"),
                            BaseUrl = "test.deribit.com",
                            ResourceName = "deribit-test.svg",
                            Title = "Test Deribit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
